### PR TITLE
InternalOnly attribute documentation

### LINKED ISSUE #37: [InternalOnly] Documentation
## Possible Solution
In PR #35 / Issue #34  we added the InternalOnly attribute. We also want to include a tutorial on how this feature can be used, as well as maybe adding a bit of inline documentation.

## Possible Implementation
1. Add a tutorial on how to use the InternalOnly attribute
2. Add an example to the example project
3. We may also want to update the usage of InternalOnlyViolationException to include the name of the method/class/property that was marked InternalOnly in the message returned with the exception

### PR DESCRIPTION
**Pull request by 96andrei**
## Description

Resolved #37 

## Related Issue

#37

### CODE REVIEW

**Comment by alexbarbato** [comment]
this looks great at a glance! I've got to dive in here in a bit and figure out why there are merge conflicts... but it looks like you may have fixed while I was typing!

**Comment by 96andrei** [comment]
Yeah, I added a message to the exception throwing, that was the conflict.

**Comment by alexbarbato** [comment]
awesome! I'm going to go through this this afternoon 👍

**Comment by alexbarbato** [comment]
I made a little tweak to how the example looked because I did a poor job of explaining the expected results. Thank you so much @96andrei!

**Pull request merged**
